server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
      - docker: {}

      - labels:
          container: container_name
          image: image
          swarm_service: swarm_service
          swarm_stack: swarm_stack
          task_name: name

      - replace:
          expression: '(?P<service>[^.]+)\.(?P<stack>[^.]+)\.(?P<rest>.+)'
          source: name
          replace: '${1}'

      - labels:
          service: service
          stack: stack
